import esbuild from "esbuild";
import process from "process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Do not edit this file directly.
*/
`;

const isProd = (process.argv[2] === "production");

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@electron/remote",
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: isProd ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
};

if (isProd) {
  await esbuild.build(buildOptions);
  process.exit(0);
} else {
  const context = await esbuild.context(buildOptions);
  await context.watch();
}
